name: Build JARVIS APK

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar SDK
        run: |
          sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.9"

      - name: Criar pasta de bibliotecas
        run: |
          mkdir -p app/libs

      - name: Baixar Sherpa-ONNX static-link
        run: |
          curl -L --fail \
            -o app/libs/sherpa-onnx-static-link-onnxruntime-1.13.7.aar \
            "https://sourceforge.net/projects/sherpa-onnx.mirror/files/v1.13.7/sherpa-onnx-static-link-onnxruntime-1.13.7.aar/download"

          ls -lh app/libs/

          test -f app/libs/sherpa-onnx-static-link-onnxruntime-1.13.7.aar

          echo "Sherpa-ONNX OK."

      - name: Baixar API Kotlin do Sherpa-ONNX
        run: |
          mkdir -p app/src/main/java/com/k2fsa/sherpa/onnx

          curl -L --fail \
            -o app/src/main/java/com/k2fsa/sherpa/onnx/Tts.kt \
            "https://raw.githubusercontent.com/k2-fsa/sherpa-onnx/master/sherpa-onnx/kotlin-api/Tts.kt"

          test -f app/src/main/java/com/k2fsa/sherpa/onnx/Tts.kt

          echo "API Kotlin OK."

      - name: Baixar Kokoro INT8 v1.0
        run: |
          rm -rf app/src/main/assets/kokoro-multi-lang-v1_0

          mkdir -p app/src/main/assets

          curl -L --fail \
            -o /tmp/kokoro.tar.bz2 \
            "https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/kokoro-int8-multi-lang-v1_0.tar.bz2"

          echo "Download concluído."

          tar -xjf /tmp/kokoro.tar.bz2 \
            -C app/src/main/assets

          rm /tmp/kokoro.tar.bz2

          echo "=============================="
          echo "ESTRUTURA DO KOKORO:"
          echo "=============================="

          find app/src/main/assets -maxdepth 4 -type f | sort

          echo "=============================="
          echo "PASTAS:"
          echo "=============================="

          find app/src/main/assets -maxdepth 3 -type d | sort

          echo "=============================="
          echo "FIM DA VERIFICAÇÃO"
          echo "=============================="

      - name: Compilar APK
        run: |
          gradle assembleDebug --no-daemon

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: JARVIS-debug
          path: app/build/outputs/apk/debug/app-debug.apk
